[colors]
[colors.primary]
background = '#000000'
foreground = '#EDE6F2'

[colors.normal]
black = '#292929'
red = '#A85861'
green = '#A0D685'
yellow = '#FFCC99'
blue = '#4F517D'
magenta = '#FF8593'
cyan = '#ADEBFF'
white = '#FFFFFF'

[colors.bright]
black = '#292929'
red = '#A85861'
green = '#A0D685'
yellow = '#FFCC99'
blue = '#4F517D'
magenta = '#FF8593'
cyan = '#ADEBFF'
white = '#FFFFFF'