general.import = [ "~/.config/anarchy/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12

[window]
padding.x = 16
padding.y = 16
decorations = "None"
opacity = 1

[selection]
save_to_clipboard = true