[ui.window.box]
width = 640
min_width = 640
max_width = 680
height = 340
min_height = 340
max_height = 400

# List constraints are critical - without these, the window shrinks when empty
[ui.window.box.scroll.list]
height = 320
min_height = 320
max_height = 340

[ui.window.box.scroll.list.item.icon]
pixel_size = 36