default:
    echo 'Hello, world!'
install_nvidia_dgpu_driver:
    source ~/.local/share/anarchy/default/just/01-install-nvidia-dgpu-drivers.sh
install_docker:
    source ~/.local/share/anarchy/default/just/02-install-docker.sh