default:
    echo 'Hello, world!'
install-nvidia-dgpu-driver:
    source ~/.local/share/anarchy/default/just/01-install-nvidia-dgpu-drivers.sh
install-docker:
    source ~/.local/share/anarchy/default/just/02-install-docker.sh